name: Home Assistant Add-on CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Add-On Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Home Assistant Add-on Linter
        uses: frenck/action-addon-linter@v2
        with:
          path: './vu-server-addon'