name: Release

on:
  release:
    types: [published]

env:
  VERSION: ${{ github.event.release.tag_name }}

jobs:
  build:
    name: Build and publish add-on
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push add-on
        uses: home-assistant/builder@master
        with:
          args: --target vu-server-addon --all --version "${VERSION#v}"